### ISSUE TITLE
Won't support compressed files (gzip)

### ISSUE THREAD

**Issue by ivansabik** [aws-samples/amazon-kinesis-replay#7]
While trying out this lib to consume s3 objects which were delivered with Kinesis Firehose to s3 in compressed gzip format I get this error:

```
2021-11-17 13:33:38 [main] INFO   EventReader - reading object s3://bucket/prefix/objects/2021/11/16/00/object-2-2021-11-16-00-00-08-959487e4-754a-46e0-9b2d-f8cf1ce8a226.gz
Exception in thread "main" com.amazonaws.SdkClientException: Unable to parse Json String.
	at com.amazonaws.util.json.Jackson.fromJsonString(Jackson.java:66)
	at com.amazonaws.samples.kinesis.replay.events.JsonEvent$Parser.parse(JsonEvent.java:56)
	at com.amazonaws.samples.kinesis.replay.utils.EventReader.next(EventReader.java:158)
	at com.amazonaws.samples.kinesis.replay.utils.EventReader.next(EventReader.java:146)
	at com.amazonaws.samples.kinesis.replay.utils.EventReader.<init>(EventReader.java:57)
	at com.amazonaws.samples.kinesis.replay.StreamPopulator.<init>(StreamPopulator.java:71)
	at com.amazonaws.samples.kinesis.replay.StreamPopulator.main(StreamPopulator.java:137)
Caused by: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Object (start marker at [Source: (String)"{"; line: 1, column: 1])
 at [Source: (String)"{"; line: 1, column: 2]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:664)
	at com.fasterxml.jackson.core.base.ParserBase._handleEOF(ParserBase.java:486)
	at com.fasterxml.jackson.core.base.ParserBase._eofAsNextChar(ParserBase.java:498)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipWSOrEnd(ReaderBasedJsonParser.java:2360)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:905)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:208)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726)
	at com.amazonaws.util.json.Jackson.fromJsonString(Jackson.java:64)
	... 6 more
```

Would be great if this lib could support compressed GZIP files as created by Kinesis Firehose. Not a Java guy, otherwise I'd try to contribute it myself.

**Comment by ivansabik** [comment]
Looks like this repo is used for a workshop or example specifically. So I'm going to take a stab at contributing to a python [lib](https://github.com/bufferapp/restream) for that. Thanks anyway!

**Comment by sthm** [comment]
This is odd as the code should support reading compressed data.

https://github.com/aws-samples/amazon-kinesis-replay/blob/master/src/main/java/com/amazonaws/samples/kinesis/replay/utils/EventReader.java#L136-L141

Maybe the compression algorithm isn't supported by commons-compress?

**Comment by sthm** [comment]
Looking at the error message, it seems like the data is actually decompressed, but cannot be parsed correctly. The application assumes one json object per line. Can you verify if the object generated by Amazon Kinesis Data Firehose contains one or multiple objects per line?
